Fix TS2345 error in NewClientDialog
The error TS2345 was occurring because the `name` property was optional in the type being passed to the `addClient` function, but it's required in the `Client` type. This commit ensures that the `name` property is always present when calling `addClient`.